[card.rexne-nightmare-king]
id = 420691
name = "Rexne the Nightmare King"
attribute = "dark"
level = 7
type = "monster normal"
race = "zombie"
set = "nightmare-king"
flavor-text = '''Rexne was once human but died to the heretics of the Wet Dream Church. Now king of the beastly, Nightmare World, he invades other worlds with his army to conquer them and feel more pleasure.'''
atk = 3000
def = 3000
ot = "CUSTOM"

[card.pleasure-painter]
id = 420692
name = "Pleasure Painter"
attribute = "dark"
level = 2
type = "monster normal tuner"
race = "zombie"
set = "nightmare-king"
flavor-text = '''When Rexne became the Nightmare King, these monsters were born. These nightmarish artists create artwork of beautiful women masturbating to the most twisted things imaginable.'''
atk = 400
def = 200
ot = "CUSTOM"

[card.horniness-from-nightmares]
id = 420693
name = "Horniness from the Nightmare World"
attribute = "dark"
level = 3
pendulum-scale = 7
type = "monster effect pendulum"
race = "zombie"
set = "nightmare-king"
effect = '''If this card is sent from your hand or Deck to your GY by an opponent's card effect: Special Summon this card.'''
atk = 1700
def = 1500
ot = "CUSTOM"

[card.corruption-from-nightmares]
id = 420694
name = "Corruption from the Nightmare World"
attribute = "dark"
level = 7
pendulum-scale = 1
type = "monster effect pendulum"
race = "zombie"
set = "nightmare-king"
effect = '''If this card is sent from your hand or Deck to your GY by an opponent's card effect: Special Summon this card.'''
atk = 2800
def = 3000
ot = "CUSTOM"

[card.nk-horny-maiden-serena]
id = 420695
name = "Horny Maiden Serena"
attribute = "dark"
level = 5
pendulum-scale = 5
pendulum-effect = '''If a Zombie-Type monster you control attacks a Defense Position monster, inflict piercing battle damage to your opponent.'''
type = "monster normal pendulum"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a Pokémon performer who wanted to make people smile but now, she performs for the Nightmare King and his army.'''
atk = 2000
def = 0
ot = "CUSTOM"

[card.nk-horny-maiden-lillie]
id = 420696
name = "Horny Maiden Lillie"
attribute = "dark"
level = 4
pendulum-scale = 4
pendulum-effect = '''Negate all card effects in your opponent's Pendulum Zones.'''
type = "monster normal pendulum"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a Pokémon trainer who wanted to find her father again but now, she found her new family in the Nightmare King's army.'''
atk = 1800
def = 0
ot = "CUSTOM"

[card.bone-bone]
id = 420697
name = "Bone Bone"
attribute = "dark"
level = 3
pendulum-scale = 1
pendulum-effect = '''Once per turn: You can roll a six-sided die. Until the end of this turn, increase this card's Pendulum Scale by that number (max. 7).'''
type = "monster normal pendulum"
race = "zombie"
set = "nightmare-king"
flavor-text = '''When Rexne became the Nightmare King, these monsters were born. These horny undead rodents are seekers of beautiful women for the Nightmare King. Once they found a suitable maiden, they kidnap them from their dimension, and brainwash them with the dirtiest things imaginable.'''
atk = 600
def = 600
ot = "CUSTOM"

[card.crank-a-nightmare]
id = 420698
name = "Crank-a-Nightmare"
type = "spell quick-play"
set = "nightmare-king"
effect = '''If a Level 7 or higher monster under your control was sent to the Graveyard this turn: Special Summon 1 "Nightmare King's Dragon" monster from your hand or Deck.'''
ot = "CUSTOM"

[card.nk-dragon-kalameet]
id = 420699
name = "Nightmare King's Dragon Kalameet"
attribute = "dark"
level = 8
type = "monster effect spsummon"
race = "zombie"
set = "nightmare-king nk-dragon"
effect = '''Cannot be Normal Summoned/Set. Must be Special Summoned with "Crank-a-Nightmare" and cannot be Special Summoned by other ways. This card can attack all monsters your opponent controls once each. During each of your End Phases, this card loses 500 ATK.'''
atk = 3500
def = 0
ot = "CUSTOM"

[card.nk-horny-maiden-skyla]
id = 4206910
name = "Horny Maiden Skyla"
attribute = "dark"
level = 5
pendulum-scale = 5
pendulum-effect = '''All Zombie-Type monsters gain 200 ATK. You take no battle damage from battles involving Zombie-Type monsters you control.'''
type = "monster normal pendulum"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a Pokémon Gym Leader that lived in Mistralton City who loved to flying planes but now, she wants to be with the Nightmare King.'''
atk = 2000
def = 0
ot = "CUSTOM"

[card.nk-horny-maiden-shauna]
id = 4206911
name = "Horny Maiden Shauna"
attribute = "dark"
level = 4
pendulum-scale = 4
pendulum-effect = '''If a Zombie-Type monster you control attacks a Defense Position monster, inflict piercing battle damage to your opponent.'''
type = "monster normal pendulum"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a Pokémon performer like Serena but now, she performs for the Nightmare King and his army.'''
atk = 1800
def = 0
ot = "CUSTOM"

[card.nk-horny-maiden-dawn]
id = 4206912
name = "Horny Maiden Dawn"
attribute = "dark"
level = 4
pendulum-scale = 4
pendulum-effect = '''If a Zombie-Type monster you control attacks a Defense Position monster, inflict piercing battle damage to your opponent.'''
type = "monster normal pendulum"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a Pokémon coordinator who wanted to be like her mother but now, she wants to be as sexy as Serena for the Nightmare King.'''
atk = 1800
def = 0
ot = "CUSTOM"

[card.nk-dragon-sinh]
id = 4206913
name = "Nightmare King's Dragon Sinh"
attribute = "dark"
level = 10
type = "monster effect spsummon"
race = "zombie"
set = "nightmare-king nk-dragon"
effect = '''Cannot be Normal Summoned/Set. Must be Special Summoned with "Crank-a-Nightmare" and cannot be Special Summoned by other ways. This card can attack all monsters your opponent controls once each. During each of your End Phases, this card loses 500 ATK.'''
atk = 4000
def = 0
ot = "CUSTOM"

[card.handaconda]
id = 4206914
name = "Shadowy Handaconda"
attribute = "dark"
level = 4
type = "monster normal"
race = "zombie"
set = "nightmare-king"
flavor-text = '''These nightmarish hands can corrupt anything that it touches.'''
atk = 2000
def = 1000
ot = "CUSTOM"

[card.nk-horny-maiden-iris]
id = 4206915
name = "Horny Maiden Iris"
attribute = "dark"
level = 2
pendulum-scale = 2
pendulum-effect = '''If a Zombie-Type monster you control attacks a Defense Position monster, inflict piercing battle damage to your opponent.'''
type = "monster normal pendulum"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a Pokémon trainer who wanted to be a Dragon-type Pokémon master but now, she wants to be much sexier than Serena for the Nightmare King.'''
atk = 1400
def = 0
ot = "CUSTOM"

[card.nk-horny-maiden-lana]
id = 4206916
name = "Horny Maiden Lana"
attribute = "dark"
level = 4
pendulum-scale = 4
pendulum-effect = '''If a Zombie-Type monster you control attacks a Defense Position monster, inflict piercing battle damage to your opponent.'''
type = "monster normal pendulum"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a Pokémon trainer who wanted to be a Water-type Pokémon master but now, she wants to be much sexier than Misty for the Nightmare King.'''
atk = 1800
def = 0
ot = "CUSTOM"

[card.nk-horny-maiden-may]
id = 4206917
name = "Horny Maiden May"
attribute = "dark"
level = 3
pendulum-scale = 3
pendulum-effect = '''If a Zombie-Type monster you control attacks a Defense Position monster, inflict piercing battle damage to your opponent.'''
type = "monster normal pendulum"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a Pokémon coordinator who wanted to see the world but now, she wants to see the Nightmare King more.'''
atk = 1600
def = 0
ot = "CUSTOM"

[card.nk-horny-maiden-misty]
id = 4206918
name = "Horny Maiden Misty"
attribute = "dark"
level = 5
pendulum-scale = 5
pendulum-effect = '''If a Zombie-Type monster you control attacks a Defense Position monster, inflict piercing battle damage to your opponent.'''
type = "monster normal pendulum"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a Water-type Pokémon trainer who wanted to be the best Gym Leader but now, she wants to be sexiest maiden of the Nightmare King's army.'''
atk = 2000
def = 0
ot = "CUSTOM"

[card.supreme-necromancer]
id = 4206919
name = "Supreme Necromancer"
attribute = "dark"
level = 7
type = "monster effect"
race = "zombie"
set = "nightmare-king"
effect = '''If a card(s) you control is destroyed while this card is in your hand: You can target the destroyed card(s); Special Summon this card. If Summoned this way: You can place the card(s) targeted by this effect to the same Zone it was on when it was destroyed. You can Tribute this card; banish 1 "Nightmare Giant" Fusion monster, 1 "Nightmare Giant" Synchro monster, 1 "Nightmare Giant" Xyz monster, and 1 "Nightmare Giant" Pendulum monster from your Deck, Extra Deck, field, and/or Graveyard, and if you do, Special Summon 1 "Supreme Nightmare King Rexne" from your Extra Deck.'''
atk = 2400
def = 2200
ot = "CUSTOM"

[card.supreme-nightmare-king-rexne]
id = 4206920
name = "Supreme Nightmare King Rexne"
attribute = "dark"
level = 12
rank = 12
pendulum-scale = 1
pendulum-effect = '''You can Tribute 1 "Nightmare King's Dragon" monster; Special Summon this card from your Pendulum Zone, ignoring its Summoning conditions.'''
type = "monster effect fusion synchro xyz pendulum spsummon"
race = "zombie"
set = "nightmare-king"
effect = '''(This card is also always treated as a Fusion, Synchro, and Xyz Monster, and has a Rank equal to its Level.) Must be Special Summoned with "Supreme Necromancer", and cannot be Special Summoned by other ways. If this card is Special Summoned: You can destroy as many monsters your opponent controls as possible, then each player that had a monster(s) destroyed by this effect takes damage equal to the total ATK the destroyed monsters had on the field. This card cannot attack the turn this effect is activated. While there are Fusion, Synchro, and Xyz Monsters banished and/or in any Graveyard(s), this card cannot be destroyed, also unaffected by card effects that would make it leave the field. All monsters you control are unaffected by the effects of your opponent's Fusion, Synchro, and Xyz Monsters. If this card destroys an opponent's monster by battle: You can Special Summon 2 "Nightmare Giant" monsters from your Extra Deck in Defense Position. If your opponent adds a card(s) to their hand (except during the Draw Phase): You can destroy that card(s).'''
atk = 5000
def = 5000
ot = "CUSTOM"

[card.nightmare-giant-colored-pencils]
id = 4206921
name = "Nightmare Giant Colored Pencils"
attribute = "dark"
rank = 4
type = "monster xyz effect"
race = "zombie"
set = "nightmare-king nightmare-giant"
effect = '''2 level 4 "Horny Maiden" monsters
Once per turn: You can detach 1 Xyz Material from this card to target 1 face-up card your opponent controls; destroy it.'''
atk = 1800
def = 2200
ot = "CUSTOM"

[card.nightmare-giant-rubber-band]
id = 4206922
name = "Nightmare Giant Rubber Band"
attribute = "dark"
level = 6
type = "monster synchro effect"
race = "zombie"
set = "nightmare-king nightmare-giant"
effect = '''1 "Nightmare King" Tuner + 1 or more non-Tuner "Horny Maiden" monsters
Once per turn, during your opponent's Standby Phase: You can inflict 300 damage to your opponent for each card your opponent controls. Each time your opponent Sets a Spell or Trap Card(s): Inflict 300 damage to your opponent.'''
atk = 2200
def = 1000
ot = "CUSTOM"

[card.nightmare-giant-hole-punch]
id = 4206923
name = "Nightmare Giant Hole Punch"
attribute = "dark"
level = 6
pendulum-scale = 4
pendulum-effect = '''You can reduce the battle damage you take from an attack involving a Pendulum Monster you control to 0. During your End Phase: You can destroy this card, and if you do, add 1 Pendulum Monster with 1500 or less ATK from your Deck to your hand. You can only use each Pendulum Effect of "Nightmare Giant Hole Punch" once per turn.'''
type = "monster pendulum effect"
race = "zombie"
set = "nightmare-king nightmare-giant"
effect = '''If this card battles an opponent's monster, any battle damage this card inflicts to your opponent is doubled.'''
atk = 2600
def = 2200
ot = "CUSTOM"

[card.nightmare-giant-tape]
id = 4206924
name = "Nightmare Giant Tape"
attribute = "dark"
level = 6
type = "monster fusion effect"
race = "zombie"
set = "nightmare-king nightmare-giant"
effect = '''2 "Horny Maiden" monsters
This card can attack your opponent directly if the only face-up monsters they control are EARTH, WATER, or FIRE.'''
atk = 2200
def = 1000
ot = "CUSTOM"

[card.nightmare-giant-scissors]
id = 4206925
name = "Nightmare Giant Scissors"
attribute = "dark"
rank = 5
type = "monster xyz effect"
race = "zombie"
set = "nightmare-king nightmare-giant"
effect = '''2 level 5 "Horny Maiden" monsters
Once per turn, during either player's turn, you can activate 1 of these effects.
●When a monster effect is activated on the field OR when a Normal Spell/Trap Card is activated: You can detach 1 Xyz Material from this card; the activated effect becomes "Destroy 1 Spell/Trap Card your opponent controls".
●You can detach 1 Xyz Material from this card; each player with a hand shuffles their entire hand into the Deck, then draws the same number of cards they shuffled into the Deck.'''
atk = 2800
def = 2000
ot = "CUSTOM"

[card.nightmare-giant-stapler]
id = 4206926
name = "Nightmare Giant Stapler"
attribute = "dark"
level = 6
type = "monster fusion effect"
race = "zombie"
set = "nightmare-king nightmare-giant"
effect = '''2 "Horny Maiden" monsters
This card can make a second attack during each Battle Phase. This card cannot attack your opponent directly. After damage calculation, if this card attacked an opponent's monster: Negate the effects of that monster (including in the Graveyard). If this card destroys an opponent's monster by battle: Inflict 1000 damage to your opponent.'''
atk = 2200
def = 2000
ot = "CUSTOM"

[card.nk-horny-maiden-sakura-haruno]
id = 4206927
name = "Horny Maiden Sakura Haruno"
attribute = "dark"
level = 5
pendulum-scale = 5
pendulum-effect = '''If a Zombie-Type monster you control attacks a Defense Position monster, inflict piercing battle damage to your opponent.'''
type = "monster normal pendulum"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a proud shinobi who wanted to be with Sasuke Uchiha forever but now, she wants to be with the Nightmare King instead.'''
atk = 2000
def = 0
ot = "CUSTOM"

[card.gates-to-the-nightmare-world]
id = 4206928
name = "The Gates to the Nightmare World"
type = "spell field"
set = "nightmare-king"
effect = '''All Zombie monsters you control gain 500 ATK/DEF. Once per turn, during your Main Phase: You can take up to 5 "Nightmare King" cards from your Deck and place them on top of your Deck in any order.'''
ot = "CUSTOM"