[card.rexne-nightmare-king]
id = 420691
name = "Rexne the Nightmare King"
attribute = "dark"
level = 7
type = "monster normal"
race = "zombie"
set = "nightmare-king"
flavor-text = '''Rexne was once human but died to the heretics of the Wet Dream Church. Now king of the beastly, Nightmare World, he invades other worlds with his army to conquer them and feel more pleasure.'''
atk = 3000
def = 3000
ot = "CUSTOM"

[card.pleasure-painter]
id = 420692
name = "Pleasure Painter"
attribute = "dark"
level = 2
type = "monster normal tuner"
race = "zombie"
set = "nightmare-king"
flavor-text = '''When Rexne became the Nightmare King, these monsters were born. These nightmarish artists create artwork of beautiful women masturbating to the most twisted things imaginable.'''
atk = 400
def = 200
ot = "CUSTOM"

[card.horniness-from-nightmares]
id = 420693
name = "Horniness from the Nightmare World"
attribute = "dark"
level = 3
pendulum-scale = 8
type = "monster effect pendulum"
race = "zombie"
set = "nightmare-king"
effect = '''If this card is sent from your hand or Deck to your GY by an opponent's card effect: Special Summon this card.'''
atk = 1700
def = 1500
ot = "CUSTOM"

[card.corruption-from-nightmares]
id = 420694
name = "Corruption from the Nightmare World"
attribute = "dark"
level = 7
pendulum-scale = 1
type = "monster effect pendulum"
race = "zombie"
set = "nightmare-king"
effect = '''If this card is sent from your hand or Deck to your GY by an opponent's card effect: Special Summon this card.'''
atk = 2800
def = 3000
ot = "CUSTOM"

[card.nk-horny-maiden-serena]
id = 420695
name = "Horny Maiden Serena"
attribute = "dark"
level = 5
type = "monster normal"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a Pokémon performer who wanted to make people smile but now, she performs for the Nightmare King and his army.'''
atk = 2000
def = 0
ot = "CUSTOM"

[card.nk-horny-maiden-lillie]
id = 420696
name = "Horny Maiden Lillie"
attribute = "dark"
level = 4
type = "monster normal"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a Pokémon trainer who wanted to find her father again but now, she found her new family in the Nightmare King's army.'''
atk = 1800
def = 0
ot = "CUSTOM"

[card.bone-bone]
id = 420697
name = "Bone Bone"
attribute = "dark"
level = 3
pendulum-scale = 1
pendulum-effect = '''Once per turn: You can roll a six-sided die. Until the end of this turn, increase this card's Pendulum Scale by that number (max. 7).'''
type = "monster normal pendulum"
race = "zombie"
set = "nightmare-king"
flavor-text = '''When Rexne became the Nightmare King, these monsters were born. These horny undead rodents are seekers of beautiful women for the Nightmare King. Once they found a suitable maiden, they kidnap them from their dimension, and brainwash them with the dirtiest things imaginable.'''
atk = 600
def = 600
ot = "CUSTOM"

[card.colorless-deep-fog]
id = 420698
name = "Colorless Deep Fog"
type = "trap continuous"
set = "nightmare-king"
effect = '''(This card is always treated as a "Nightmare World" card.) Once per turn: You can Special Summon 1 "Primeval Demon Token" (Fiend-Type/DARK/Level 1/ATK 500/DEF 500). During each player's End Phase, Tribute 1 Token or "Nightmare World" monster, or send this card to the Graveyard.'''
ot = "CUSTOM"

[card.primeval-demon-token]
id = 420699
name = "Primeval Demon Token"
attribute = "dark"
level = 1
type = "monster normal token"
race = "fiend"
set = "nightmare-king"
flavor-text = '''This card can be used as a "Primeval Demon Token".'''
atk = 500
def = 500
ot = "CUSTOM"

[card.nk-horny-maiden-skyla]
id = 4206910
name = "Horny Maiden Skyla"
attribute = "dark"
level = 5
type = "monster normal"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a Pokémon Gym Leader that lived in Mistralton City who loved to flying planes but now, she wants to be with the Nightmare King.'''
atk = 2000
def = 0
ot = "CUSTOM"

[card.nk-horny-maiden-shauna]
id = 4206911
name = "Horny Maiden Shauna"
attribute = "dark"
level = 4
type = "monster normal"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a Pokémon performer like Serena but now, she performs for the Nightmare King and his army.'''
atk = 1800
def = 0
ot = "CUSTOM"

[card.nk-horny-maiden-dawn]
id = 4206912
name = "Horny Maiden Dawn"
attribute = "dark"
level = 4
type = "monster normal"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a Pokémon coordinator who wanted to be like her mother but now, she wants to be as sexy as Serena for the Nightmare King.'''
atk = 1800
def = 0
ot = "CUSTOM"

[card.will-of-the-old-one]
id = 4206913
name = "Will of the Old One"
type = "spell"
set = "nightmare-king"
effect = '''(This card is always treated as a "Nightmare World" card.) Target 1 "Horny Maiden" monster you control; Fusion Summon 1 Fusion Monster from your Extra Deck that lists that monster on the field as Fusion Material, using it as the Fusion Material. You can only activate 1 "Will of the Old One" per turn.'''
ot = "CUSTOM"

[card.handaconda]
id = 4206914
name = "Shadowy Handaconda"
attribute = "dark"
level = 4
type = "monster normal"
race = "zombie"
set = "nightmare-king"
flavor-text = '''These nightmarish hands can corrupt anything that it touches.'''
atk = 2000
def = 1000
ot = "CUSTOM"

[card.nk-horny-maiden-iris]
id = 4206915
name = "Horny Maiden Iris"
attribute = "dark"
level = 2
type = "monster normal"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a Pokémon trainer who wanted to be a Dragon-type Pokémon master but now, she wants to be much sexier than Serena for the Nightmare King.'''
atk = 1400
def = 0
ot = "CUSTOM"

[card.nk-horny-maiden-lana]
id = 4206916
name = "Horny Maiden Lana"
attribute = "dark"
level = 4
type = "monster normal"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a Pokémon trainer who wanted to be a Water-type Pokémon master but now, she wants to be much sexier than Misty for the Nightmare King.'''
atk = 1800
def = 0
ot = "CUSTOM"

[card.nk-horny-maiden-may]
id = 4206917
name = "Horny Maiden May"
attribute = "dark"
level = 3
type = "monster normal"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a Pokémon coordinator who wanted to see the world but now, she wants to see the Nightmare King more.'''
atk = 1600
def = 0
ot = "CUSTOM"

[card.nk-horny-maiden-misty]
id = 4206918
name = "Horny Maiden Misty"
attribute = "dark"
level = 5
type = "monster normal"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a Water-type Pokémon trainer who wanted to be the best Gym Leader but now, she wants to be sexiest maiden of the Nightmare King's army.'''
atk = 2000
def = 0
ot = "CUSTOM"

[card.nk-soulsucker-serena]
id = 4206919
name = "Soulsucker Serena"
attribute = "dark"
level = 6
type = "monster fusion effect"
race = "zombie"
set = "nightmare-king nk-soulsucker"
flavor-text = '''Horny Maiden Serena + Primeval Demon Token
Must be Fusion Summoned with the above Fusion Materials or with "Will of the Old One". If this card is Special Summoned: Target 1 Zombie monster in your GY; equip that target to this card. Gains ATK equal to the original ATK of the monster equipped to it by this effect. Gains 100 ATK for each monster in your GY. If this card would be destroyed by battle, destroy that equipped monster instead.'''
atk = 2500
def = 500
ot = "CUSTOM"

[card.nk-horny-maiden-sakura-haruno]
id = 4206927
name = "Horny Maiden Sakura Haruno"
attribute = "dark"
level = 5
type = "monster normal"
race = "zombie"
set = "nightmare-king nk-horny-maiden"
flavor-text = '''She was a proud shinobi who wanted to be with Sasuke Uchiha forever but now, she wants to be with the Nightmare King instead.'''
atk = 2000
def = 0
ot = "CUSTOM"

[card.gates-to-the-nightmare-world]
id = 4206928
name = "The Gates to the Nightmare World"
type = "spell field"
set = "nightmare-king"
effect = '''(This card is always treated as a "Nightmare World" card.) All Zombie monsters you control gain 500 ATK/DEF. Once per turn, during your Main Phase: You can take up to 5 "Nightmare World" cards from your Deck and place them on top of your Deck in any order.'''
ot = "CUSTOM"

[card.curse-of-nightmares]
id = 4206929
name = "Curse of Nightmares"
type = "trap continuous"
set = "nightmare-king"
effect = '''(This card is always treated as a "Nightmare World" card.) Each time a Zombie monster(s) is Special Summoned, while this card is already face-up in your Spell and Trap Zone: Inflict 400 damage to your opponent.'''
ot = "CUSTOM"

[card.coronavirus-alpha]
id = 4206930
name = "Coronavirus Alpha"
attribute = "dark"
level = 1
pendulum-scale = 0
pendulum-effect = '''While this card is on the field: The turn player can Fusion Summon 1 Fusion Monster from their Extra Deck, by banishing Fusion Materials listed on it from their hand or field.'''
type = "monster normal pendulum"
race = "fiend"
set = "nightmare-king"
flavor-text = '''The deadly coronavirus originated in the Nightmare World within the Bone Bone monsters. It is believed that these viruses are antibodies for their bones.'''
atk = 0
def = 0
ot = "CUSTOM"

[card.coronavirus-omega]
id = 4206931
name = "Coronavirus Omega"
attribute = "dark"
level = 1
pendulum-scale = 13
pendulum-effect = '''While this card is on the field: The turn player can Fusion Summon 1 Fusion Monster from their Extra Deck, by banishing Fusion Materials listed on it from their hand or field.'''
type = "monster normal pendulum"
race = "fiend"
set = "nightmare-king"
flavor-text = '''The deadly coronavirus originated in the Nightmare World within the Bone Bone monsters. It is believed that these viruses are antibodies for their bones.'''
atk = 0
def = 0
ot = "CUSTOM"

[card.origami-castle]
id = 4206932
name = "King Olly's Origami Castle"
type = "spell field"
set = "nightmare-king"
effect = '''Once per turn, if a card(s) is added from the Main Deck to your opponent's hand (except during the Damage Step): You can Special Summon 1 "Nightmare World" monster from your Deck in Defense Position. If you Special Summon a "Nightmare World" monster(s) during your opponent's turn (except during the Damage Step): You can Special Summon as many "Origami Tokens" (Fiend/DARK/Level 4/ATK 1800/DEF 1200) as possible in Attack Position, but destroy them during the End Phase (even if this card leaves the field). You can only use this effect of "King Olly's Origami Castle" once per turn.'''
ot = "CUSTOM"

[card.origami-token]
id = 4206933
name = "Origami Token"
attribute = "dark"
level = 4
type = "monster normal token"
race = "fiend"
set = "nightmare-king"
flavor-text = '''This card can be used as a "Origami Token".'''
atk = 1800
def = 1200
ot = "CUSTOM"