[set.nightmare-king]
code = 0x420
name = '''Nightmare World'''

[set.nk-horny-maiden]
code = 0x420a
name = '''Horny Maiden'''

[set.nk-dragon]
code = 0x420b
name = '''Nightmare King's Dragon'''

[set.nightmare-giant]
code = 0x420c
name = '''Nightmare Giant'''