[set.nightmare-king]
code = 0x420
name = '''Nightmare World'''

[set.nk-horny-maiden]
code = 0x420a
name = '''Horny Maiden'''

[set.nk-nt]
code = 0x420b
name = '''Nightmare Tech'''

[set.nk-black-phantom]
code = 0x420c
name = '''Black Phantom'''